Parameters:
  BucketName:    
    Description: Name of the Bucket
    Type: String
    Default: awx-backup
Resources:
  AWXBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ '-', [!Ref BucketName, !Ref "AWS::StackId"] ]
      LifecycleConfiguration: 
        Rules:
          - ExpirationInDays: 60
            Status: Enabled
            Transition: 
              StorageClass: GLACIER
              TransitionInDays: 14